name: game_quiz
description: "MVP Game Quiz App utlizing Gaming Quiz API https://rapidapi.com/devsdocs/api/game-quiz"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.1
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
